### ISSUE TITLE
Implement Color > Settings >`clear()`

### ISSUE THREAD

**Issue by matthew-carroll** [matthew-carroll/flutter_processing#116]
Implement Color > Settings >`clear()`

**Comment by ThangVuNguyenViet** [comment]
Hi Matt. I want to be assigned to this feature. This should set the background color to 0x00000000. Is that cool to you?

**Comment by matthew-carroll** [comment]
Sure, go for it. Please make sure your implementation honors the standard Processing behavior, please follow the Contributing Guide, and please make your best effort to match your work to the similar work that already exists. Thanks!
