### ISSUE TITLE
Make sketch a StateMixin to avoid having to call sketch.foo()

### ISSUE THREAD

**Issue by mbaumgartenbr** [matthew-carroll/flutter_processing#26]
Hey Mattew!

Great work with this package, I'm loving the youtube series.

In the videos you say that in processing we would be able to call `foo()` directly without `Sketch`. I know nothing about processing and I'm also not an expert with flutter, so I was thinking if we couldn't have the `Sketch` class as a state mixin:

```dart
mixin SketchStateMixin<S extends State> on State<S> {
  // You could also annotate with @mustCallSuper to call _doSetup and stuff
  void draw();
  void setup();
}

// And when creating the `Processing` widget:

class MyWidget extends StatefulWidget {
  @override
  _MyWidgetState createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> with SketchStateMixin {

  @override
  void setup() {
    // TODO user setup
  }

  @override
  void draw() {
    // TODO user draw stuff
  }

  @override
  Widget build(BuildContext context) {
    return Processing(
      sketch: this,
    );
  }
}
```
 It's just a thought I had and I haven't tried anything neither know if this would work.
 
Cheers!

**Comment by matthew-carroll** [comment]
Hi @mbaumgartenbr, thanks for the suggestion. That could be something worth investigating once we solidify some of the major capabilities like bitmap reading/writing. We'll need to see how the tricky relationships work out.

**Comment by matthew-carroll** [comment]
I recently broke down the structure of flutter_processing and I didn't come across any particular need for this change. I'm going to close this issue because it's not currently a priority. If you see a specific in the future to make this change, please feel free to open a new issue.
