### ISSUE TITLE
Test Exception in pumpWidget. (test/shape/strokeWeight invalid value test)

### ISSUE THREAD

**Issue by ltOgt** [matthew-carroll/flutter_processing#30]
In your latest [video](https://www.youtube.com/watch?v=Aig6oLqVdcQ) you asked if someone knows how to catch exceptions from within `pumpWidget`

`tester.pumpWidget` descriptions reads:

This method should not be used as the first parameter to an [expect] or [expectLater] call to test that a widget throws an exception.
Instead, use [TestWidgetsFlutterBinding.takeException].

```dart
testWidgets('MyWidget asserts invalid bounds', (WidgetTester tester) async {
  await tester.pumpWidget(MyWidget(-1));
  expect(tester.takeException(), isAssertionError); // or isNull, as appropriate.
});
```

I would expect the adjusted test to be:
```dart
testWidgets('strokeWeight() invalid value', (tester) async {
  configureWindowForSpecTest(tester);

  await tester.pumpWidget(
    Processing(
      sketch: Sketch.simple(
        draw: (s) {
          s
            ..noLoop()
            ..strokeWeight(-1);
        },
      ),
    ),
  );
  expect(tester.takeException(), isA<Exception>());
});
```

However `<actual>` is still null:
```
The following TestFailure object was thrown running a test:
  Expected: <Instance of 'Exception'>
  Actual: <null>
   Which: is not an instance of 'Exception'
```

**Comment by matthew-carroll** [comment]
Thanks. I'll make the change when I get a minute.

**Comment by matthew-carroll** [comment]
I marked this as a "good first issue" for anyone who wants to try committing this fix. Please see the CONTRIBUTING guide for details.
