### ISSUE TITLE
How to contribute to the project

### ISSUE THREAD

**Issue by Azzeccagarbugli** [matthew-carroll/flutter_processing#32]
Hey Matthew! 

First of all thanks for this fancy porting, it's a wonderful idea.

I really would love to support you with the project, but I don't know which standard should I follow, so could you please write a **CONTRIBUTING** file in which explain us how to help you out? In this way we can improve the efficacy of the nexts pull requests.  

In the [PR](https://github.com/matthew-carroll/flutter_processing/pull/31) that I just made for example I noticed that when I formatted the code _(using VS Code)_ everything was completely moved so I guess that having a common guideline would be better.

Cheers 👋

**Comment by mark-apn** [comment]
I would also love to participate (if you're open to contributions) and a contributing file would help there :-)

**Comment by matthew-carroll** [comment]
Thanks for asking about contributing. I think that until the project reaches something close to 1.0 it can't really support outside contributions. Everything is tied together in one file, which eventually needs to be split apart. That requires careful coordination and planning. As it happens, I've made some fundamental changes in the past couple weeks to support bitmap operations.

Once the project reaches a certain level of completeness and stability then I can hopefully switch from the developer to the project lead and review PRs.

At this point in the project, the most valuable way to contribute would be to dig into the non-trivial behaviors:

- bitmap manipulation without needing to copy data to/from the Flutter engine
- shader programming
- 3D rendering

Topics like that will probably require convincing Flutter to make some changes or add some features, or it will require that this project take on some significant dependencies. In any event, the most impactful help would happen in areas where the approach and solution isn't obvious.

**Comment by matthew-carroll** [comment]
I've added a `CONTRIBUTING` guide. I'll have a video coming out in a few weeks that walks through it.
