### ISSUE TITLE
i like it very well !

### ISSUE THREAD

**Issue by peter100u** [matthew-carroll/flutter_processing#57]
i like it very well !
https://pub.dev/packages/flutter_processing/example

I like this library very much. I hope it can do better, but this example is not the best in your pub. I hope you can do better and update it, so that more people can pay attention to and spread it

**Comment by matthew-carroll** [comment]
Thanks. The project, including the example app are constantly changing. I'm sure it will get better. In the future, please reserve these issues for specific, actionable requests and bugs.
