### ISSUE TITLE
please support null safety version, thank your very much

### ISSUE THREAD

**Issue by peter100u** [matthew-carroll/flutter_processing#58]
Xcode's output:
↳
    Error: Cannot run with sound null safety, because the following dependencies
    don't support null safety:

     - package:flutter_processing

    For solutions, see https://dart.dev/go/unsound-null-safety

**Comment by matthew-carroll** [comment]
This is an issue with the public release. I haven't released an update in a long time. The next release will support null safety. Or you can reference this GitHub repo directly in your pubspec.yaml. Please check pubspec syntax for how to do that.
