### ISSUE TITLE
Various events cannot be responded to on your phone

### ISSUE THREAD

**Issue by peter100u** [matthew-carroll/flutter_processing#75]
I found that various events using the stetch, such as clicking, moving, holding, etc., were invalid, and after looking at your source code and knowing that it was _ProcessingState class of event logic, using if 
`if (event.kind != PointerDeviceKind.mouse) {
      return;
    }`
    Why is it blocking?

**Comment by peter100u** [comment]
The mousePressed callback is not performed


`
class SuperDrawPadPage extends StatefulWidget {
  const SuperDrawPadPage({Key? key}) : super(key: key);

  @override
  _SuperDrawPadPageState createState() => _SuperDrawPadPageState();
}

class _SuperDrawPadPageState extends ProcessingState<SuperDrawPadPage> {
  @override
  Sketch createSketch() {
    return Sketch.simple(
        setup: (Sketch sketch) async {
          sketch.size(width: Get.width.toInt(), height: Get.height.toInt());
        },
        draw: (Sketch sketch) async {},
        mousePressed: (Sketch sketch) {
          print('peter mouse pressed');
        },
        mouseDragged: (sketch) {
          sketch.circle(
              center:
                  Offset(sketch.mouseX.toDouble(), sketch.mouseY.toDouble()),
              diameter: 10);
        });
  }

  @override
  String get gifFilepath => "";
}`


why is https://github.com/matthew-carroll/flutter_processing/issues/75#issue-1001834918

**Comment by matthew-carroll** [comment]
What version of the package are you using?

**Comment by peter100u** [comment]
I'm not using the package, I'm using git 
`flutter_processing:
    git:
      url: https://github.com/matthew-carroll/flutter_processing.git`

**Comment by matthew-carroll** [comment]
I've verified that mouse callbacks work on Mac OS and Web without issue, but they don't seem to work on iOS (at least). 

This may be a Flutter bug with the `Listener` widget on mobile. I'll need to investigate further to be sure.

**Comment by peter100u** [comment]
Thank you very much for your reply and look forward to your fix and additional processing api

**Comment by peter100u** [comment]
I feel that when drawing circles and lines and other shapes, it is very blurry. I don’t know if there is no smooth, because there is no implementation of smooth and other apis 
Figure 1 is a dot implemented with processing, and Figure 2 is a dot implemented with flutter_processing
![3741632403988_ pic](https://user-images.githubusercontent.com/14010579/134516583-61b51c3a-5ecc-4506-a651-da244c1bb2c1.jpg)

![3751632404030_ pic](https://user-images.githubusercontent.com/14010579/134516608-35f45d5a-009c-44a8-a973-890103c87191.jpg)
