### ISSUE TITLE
rect() API

### ISSUE THREAD

**Issue by davidmartos96** [matthew-carroll/flutter_processing#9]
I've just seen the video on the rect and square implementation. Nice job!
I was wondering why you chose `rect` as a named argument. I think using the `rect` as a positional argument and the border radius as named would look cleaner, the same as you did with the square method.

Keep up the great work!

**Comment by matthew-carroll** [comment]
Thanks for watching.

No particular reason. I tend to either use all positional arguments or all named arguments. It's just a habit and a preference. 

For questions like this, the YouTube comments are probably a more appropriate place to ask. I try to respond to all specific technical questions that people ask in the video comments. I think the repo issues should be reserved for bugs and feature requests.
