### ISSUE TITLE
Progress issues

### ISSUE THREAD

**Issue by peter100u** [matthew-carroll/flutter_processing#95]
The update frequency of the boss is a little low recently. Do you intend to do it for a long time or according to the actual situation? Is this your main energy range? I won't abandon this project in the future. I'm very nervous

**Comment by matthew-carroll** [comment]
I'm not sure what that means. When filing issues, please follow the guidance in the CONTRIBUTING guide: https://github.com/matthew-carroll/flutter_processing/blob/main/CONTRIBUTING.md

I'm going to close this ticket because I don't know what you're asking for.
