### ISSUE TITLE
PVector set(x,y) show 0,0

### ISSUE THREAD

**Issue by peter100u** [matthew-carroll/flutter_processing#96]
When I use the pvector. Set () method, the result should be (0,0)

**Comment by peter100u** [comment]
PVector tempVector = PVector(0, 0);
tempVector.set(10, 10);
print('vector ' + tempVector.toString());

It is wrong to always return the initial number of the construct

**Comment by matthew-carroll** [comment]
What is the expected value in your example, and what is the actual value?
