### ISSUE TITLE
Mobile event support

### ISSUE THREAD

**Issue by SamuelMauricioL** [matthew-carroll/flutter_processing#97]
Hi @ matthew-carroll I was trying to move your example from snake_game to mobile but I came across that the Sketch class only supports sending desktop events.

![image](https://user-images.githubusercontent.com/67238016/149039994-c7947633-95bb-4ee4-8660-6811374f8395.png)

I was wondering if there is any way for these events to be launched from the ontap () property of a Widget, that way it opens up more freedom when implementing any functionality and expanding the examples to mobiles.

I don't know if something like this interrupts the draw () or if there is a less intrusive way to emit events and create reactions from the mobile.

Thank you for your time and for creating a wonderful package.

**Comment by peter100u** [comment]
https://github.com/matthew-carroll/flutter_processing/issues/75

Ha ha, I thought I was the only one who paid attention to this project. I also found this problem, but the work is too busy. I've been busy with super recently_ The edit project, I don't know whether it is continuously updated, and I thank the author for providing this library, but it's far from active enough

**Comment by matthew-carroll** [comment]
@SamuelMauricioL do you have a recommendation for the event mapping? I suppose we can map `mousePressed`, `mouseDragged`, `mouseReleased`, and `mouseClicked`, but I don't think `mouseMoved` would make any sense on mobile.
